version       = "0.0.0"
author        = "Florian Schroedl"
description   = "Nim utils"
license       = "MIT"

requires "nim >= 1.6.2"
requires "https://github.com/floscr/nimfp#20cd14ae0bc4e7e2ecb2585864887b9feb65a6d7"
requires "fusion"
requires "argparse"
requires "print"
requires "nimbluez"
